{{- if eq .Values.exposure.type "istioGateway" -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "nexspence.fullname" . }}-istio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexspence.labels" . | nindent 4 }}
  {{- with .Values.exposure.istioGateway.vsAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- range .Values.exposure.hosts }}
    - {{ .host | quote }}
    {{- end }}
  gateways:
    - {{ default (printf "%s-istio" (include "nexspence.fullname" .)) .Values.exposure.istioGateway.existingGateway }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "nexspence.fullname" . }}
            port:
              number: {{ .Values.service.port }}
      timeout: {{ .Values.exposure.istioGateway.timeout }}
{{- end }}
