{{- if and (eq .Values.exposure.type "istioGateway") (not .Values.exposure.istioGateway.existingGateway) -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "nexspence.fullname" . }}-istio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexspence.labels" . | nindent 4 }}
spec:
  selector:
    {{- toYaml .Values.exposure.istioGateway.gatewaySelector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.exposure.istioGateway.port }}
        name: http
        protocol: {{ if .Values.exposure.istioGateway.tlsMode }}HTTPS{{ else }}HTTP{{ end }}
      hosts:
        {{- range .Values.exposure.hosts }}
        - {{ .host | quote }}
        {{- end }}
      {{- if .Values.exposure.istioGateway.tlsMode }}
      tls:
        mode: {{ .Values.exposure.istioGateway.tlsMode }}
        {{- if .Values.exposure.istioGateway.tlsSecret }}
        credentialName: {{ .Values.exposure.istioGateway.tlsSecret }}
        {{- end }}
      {{- end }}
{{- end }}
